-- Migration: Add description_th column to tcas_programs table
-- Created: 2026-03-23
--
-- Run this in Supabase Dashboard → SQL Editor
-- Or: psql $DATABASE_URL -f add-tcas-description-column.sql

-- Add description_th column for Thai program descriptions
ALTER TABLE public.tcas_programs
    ADD COLUMN IF NOT EXISTS description_th TEXT;

-- Create index for faster queries on non-null descriptions
CREATE INDEX IF NOT EXISTS idx_tcas_programs_description_th ON public.tcas_programs(description_th)
    WHERE description_th IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.tcas_programs.description_th IS 'Thai description of the program (2-3 sentences) generated by Gemini API';

-- Verify column was added
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'tcas_programs'
AND column_name = 'description_th';
