import { StyleSheet } from "react-native";
import {
  PageBg,
  Text as ThemeText,
  Border,
  Shadow,
  Radius,
  Gradient,
  Accent,
  Space,
  Type,
} from "../../lib/theme";
import { ANIMATION_CONFIG } from "./constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PageBg.default,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: PageBg.default,
    justifyContent: "center",
    alignItems: "center",
    gap: Space.lg,
  },
  loadingText: {
    fontSize: Type.body.fontSize,
    color: ThemeText.tertiary,
  },

  stickyHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: "rgb(206, 206, 206)",
  },
  stickyHeaderContent: {
    height: ANIMATION_CONFIG.smallTitleHeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Space["2xl"],
  },
  smallTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Space.sm,
  },
  smallLogoImage: {
    width: 24,
    height: 24,
  },
  smallHeaderTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: ThemeText.primary,
  },
  compactSearchContainer: {
    position: "absolute",
    right: Space["2xl"],
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  compactSearchButton: {
    width: 36,
    height: 36,
    borderRadius: Radius.full,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Border.default,
    ...Shadow.neutral,
  },
  compactSearchIcon: {
    fontSize: 16,
  },

  inlineSearchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: Space.sm,
  },
  inlineSearchInput: {
    flex: 1,
    height: 36,
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    borderRadius: 10,
    paddingHorizontal: Space.lg,
    fontFamily: "LibreFranklin_400Regular",
    fontSize: 17,
    color: ThemeText.primary,
  },
  inlineSearchCancelButton: {
    paddingHorizontal: Space.sm,
    paddingVertical: Space.xs,
  },
  inlineSearchCancelText: {
    fontSize: 17,
    color: Accent.blue || "#007AFF",
    fontWeight: "400",
  },

  scrollView: {
    flex: 1,
  },
  scrollContent: {
    gap: Space["2xl"],
  },

  header: {
    paddingHorizontal: Space["2xl"],
    paddingBottom: Space.md,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Space.md,
    gap: Space.md,
  },
  logoImage: {
    width: 36,
    height: 36,
  },
  headerTitle: {
    fontSize: 34,
    fontWeight: "700",
    color: ThemeText.primary,
    letterSpacing: -0.5,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Border.default,
    paddingHorizontal: Space.lg,
    height: ANIMATION_CONFIG.searchBarHeight,
    gap: Space.sm,
    ...Shadow.neutral,
  },
  searchIcon: {
    fontSize: 18,
  },
  searchInput: {
    flex: 1,
    fontFamily: "LibreFranklin_400Regular",
    fontSize: Type.body.fontSize,
    color: ThemeText.primary,
  },

  section: {
    gap: Space.md,
  },
  coverageCard: {
    marginHorizontal: Space["2xl"],
    marginTop: Space.sm,
    backgroundColor: "#FFFFFF",
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Border.default,
    padding: Space.lg,
    gap: Space.sm,
    ...Shadow.neutral,
  },
  hackathonHeroWrap: {
    marginTop: Space.md,
    width: "100%",
    alignSelf: "stretch",
    borderRadius: 0,
    borderWidth: 0,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    overflow: "hidden",
    aspectRatio: 16 / 9,
    backgroundColor: "#020C1A",
  },
  hackathonHero: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  hackathonVignette: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  hackathonHeroContent: {
    ...StyleSheet.absoluteFillObject,
    paddingHorizontal: Space["2xl"],
    paddingVertical: Space.xl,
    zIndex: 2,
    justifyContent: "space-between",
  },
  hackathonTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  hackathonLogo: {
    height: 56,
    width: 56 * 2.5, // 140 width - matches the native 4096x1636 aspect ratio exactly so it aligns left natively
    opacity: 0.9,
    marginBottom: Space.xs,
  },
  hackathonSubtitle: {
    fontSize: 12,
    color: "#00F0FF",
    fontWeight: "700",
    letterSpacing: 4,
    textTransform: "uppercase",
    textShadowColor: "rgba(0,240,255,0.5)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  hackathonBody: {
    fontSize: 15,
    lineHeight: 22,
    color: "rgba(255,255,255,0.75)",
    letterSpacing: 0.5,
    maxWidth: "80%",
  },
  hackathonBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  hackathonMetaContainer: {
    gap: Space.xs,
  },
  hackathonMetaPill: {
    backgroundColor: "rgba(0,240,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(0,240,255,0.2)",
    paddingHorizontal: Space.md,
    paddingVertical: 5,
    borderRadius: Radius.sm,
    alignSelf: "flex-start",
    shadowColor: "#00F0FF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  hackathonMetaText: {
    fontSize: 11,
    color: "#00F0FF",
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  hackathonClickHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: Space.xs,
    opacity: 0.9,
  },
  hackathonClickText: {
    fontSize: 12,
    color: "#00F0FF",
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
    textShadowColor: "rgba(0,240,255,0.8)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  hackathonClickArrow: {
    fontSize: 15,
    color: "#00F0FF",
    textShadowColor: "rgba(0,240,255,0.8)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  hackathonLetterboxTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundColor: "#000",
    zIndex: 10,
  },
  hackathonLetterboxBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundColor: "#000",
    zIndex: 10,
  },
  coverageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Space.md,
  },
  coverageTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: ThemeText.primary,
  },
  coveragePercent: {
    fontSize: 20,
    fontWeight: "700",
    color: Accent.green,
  },
  coverageSubtitle: {
    fontSize: 12,
    color: ThemeText.tertiary,
  },
  coverageBarTrack: {
    height: 10,
    borderRadius: Radius.full,
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    overflow: "hidden",
  },
  coverageBarFill: {
    height: "100%",
    borderRadius: Radius.full,
    backgroundColor: Accent.green,
  },
  coverageStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Space.md,
  },
  coverageStat: {
    fontSize: 12,
    color: ThemeText.secondary,
  },
  sectionTitle: {
    fontSize: Type.label.fontSize,
    color: ThemeText.tertiary,
    textTransform: Type.label.textTransform,
    letterSpacing: Type.label.letterSpacing,
    marginBottom: Space.xs,
    paddingHorizontal: Space["2xl"],
  },
  sectionGrid: {
    flexDirection: "row",
    gap: Space.md,
    paddingHorizontal: 0,
    paddingRight: Space["2xl"],
  },
  fullWidthScroll: {
    marginHorizontal: -5,
  },

  compactTitle: {
    fontSize: 14,
    color: "#FFFFFF",
    lineHeight: 18,
    marginBottom: Space.xs,
  },
  compactSlogan: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.85)",
    lineHeight: 14,
  },
  // Shadow on wrapper only — do not use overflow:hidden here or iOS clips the shadow
  // and corners look harsh. Inner compactCard clips image + border to the radius.
  compactCardWrapper: {
    width: 140,
    marginRight: 0,
    borderRadius: Radius.xl,
    ...Shadow.neutral,
  },
  compactCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Border.default,
    overflow: "hidden",
    height: 240,
    position: "relative",
  },
  compactCardPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  compactImageFull: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    borderRadius: Radius.xl,
    backgroundColor: Gradient.masterCard[1],
  },
  compactImagePlaceholder: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Gradient.masterCard[1],
  },
  compactImageIcon: {
    fontSize: 48,
  },
  compactOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: Space.md,
    paddingTop: 40,
    gap: Space.xs,
    justifyContent: "flex-end",
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Space.sm,
    marginTop: Space.xs,
  },
  progressLabel: {
    fontSize: 10,
    color: "rgba(255,255,255,0.9)",
    minWidth: 22,
  },
  progressBarContainer: {
    flex: 1,
    height: 4,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: Accent.green,
    borderRadius: 2,
  },
  emptyCard: {
    width: 140,
    backgroundColor: "transparent",
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: "rgba(206, 206, 206, 0.5)",
    borderStyle: "dashed",
    height: 240,
    marginRight: 0,
  },
  doneBadge: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    paddingVertical: 3,
    paddingHorizontal: Space.sm,
    borderRadius: Radius.md,
    alignSelf: "flex-start",
  },
  doneBadgeText: {
    fontSize: 10,
    color: Accent.green,
    fontFamily: "LibreFranklin_400Regular",
  },

  quickLinks: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Space.md,
    paddingHorizontal: Space["2xl"],
  },
  quickLinkCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Border.default,
    padding: Space.lg,
    width: "47%",
    ...Shadow.neutral,
  },
  quickLinkPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  quickLinkIcon: {
    fontSize: 28,
    marginBottom: Space.sm,
  },
  quickLinkTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: ThemeText.primary,
    marginBottom: Space.xs,
  },
  quickLinkSubtitle: {
    fontSize: 12,
    color: ThemeText.tertiary,
  },
});
